[package]
name = "tui-file-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
cacao = "0.3.2"
color-eyre = "0.6.5"
crossterm = "0.29.0"
pasteboard = "0.1.3"
ratatui = "0.29.0"
tokio =  { version = "1.28.2", features = ["full"] }
tui-textarea = "0.7.0"
